# .python-app.yml
name: Python application

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    # Install project dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Execute test and generate report
    - name: Test with pytest
      run: |
        pytest --junitxml=results/test-results.xml src/tests.py

    # Install Test IT CLI and submit test results to TMS
    - name: Submit results
      if: always()
      run: |
        pip install testit-cli
        testit results import \
          --url https://team-t71g.testit.software/ \
          --project-id 050d0287-f129-4640-8ac0-62dc3909c580 \
          --configuration-id 88fd331d-dcd3-4f40-929f-f9a01f10c4f4 \
          --testrun-name "GitHub test run" \
          --results results/test-results.xml
